In [1]:
using TensorOperations
using LinearAlgebra

In [2]:
H = convert(Array{ComplexF64,2}, [1/sqrt(2) 1/sqrt(2); 1/sqrt(2) -1/sqrt(2)])

2×2 Array{Complex{Float64},2}:
 0.707107+0.0im   0.707107+0.0im
 0.707107+0.0im  -0.707107+0.0im

In [3]:
init_zero = convert(Array{ComplexF64,1}, [1, 0])
res = zeros(ComplexF64, 2)
@tensor begin
    res[a] = H[a, b] * init_zero[b]
end


2-element Array{Complex{Float64},1}:
 0.7071067811865475 + 0.0im
 0.7071067811865475 + 0.0im

In [7]:
H *H * H * H * init_zero

2-element Array{Complex{Float64},1}:
 0.9999999999999997 + 0.0im
                0.0 + 0.0im